Algoritmo "ATIVIDADE4-procedimento"
// Disciplina   : [FRONT-END]
// Professor   : Victor Rohod
// Descrição   : 4. Faça um programa utilizando função ou procedimento
// que leia 5 números
// e informe quantos desses números  são maiores que 10.
// Autor(a)    : Raul S Siqueira
// Data atual  : 07/03/2024
Var
// Seção de Declarações das variáveis 
num : inteiro

procedimento numeros > 0
 total <- nuemros

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo