Algoritmo "ex1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2024
Var
contador : inteiro


Inicio
para contador <- 1 ate 100 passo 1 faca
  se (contador % 10 = 0) entao
    escreval(contador, " Multiplo de 10")
  senao
    escreval(contador)
  fimSe
fimPara


Fimalgoritmo