Algoritmo "ex3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2024
Var
contador : inteiro


Inicio
contador <- 1
enquanto (contador <= 10) faca
  escreval(contador," x 8 = ",contador*8)
  contador <- contador + 1
fimEnquanto


Fimalgoritmo